### ISSUE TITLE
Good job pedrila

### ISSUE THREAD

**Issue by emcifuntik** [Keiichi32/altv-cheat#1]

**Comment by 7Hazard** [comment]
👍 Very good haker, thnx for finding vulnerabilities for us

**Comment by Keiichi32** [comment]
![Screenshot 2020-12-02 014324](https://user-images.githubusercontent.com/44448654/100813511-c9505080-343f-11eb-9d30-029c8cc61367.png)
@emcifuntik @7Hazard no need to thank me

**Comment by Keiichi32** [comment]
@7Hazard bazdmeg

**Comment by Jozsefvaroshook** [comment]
> _No description provided._

Nice iq u sell? Probably u are a russian little shithead.
Alt:V cheat > Alt:V and Részeg Péter hook

**Comment by martonp96** [comment]
@Keiichi32 https://www.youtube.com/watch?v=eL_0Ok_Gkas
